диплом часть 3. добавил комментарии
zoomja/java-explore-with-me pull request #3
Opened 2024-11-20 22:07 UTC by zoomja

2024-11-22 05:57 UTC, VadimZharkov reviewed
В родительском pom зависимость
spring-boot-starter-data-jpa лишняя, т.к. она нужна не для всех модулей.

2024-11-22 06:02 UTC, VadimZharkov reviewed
Свойства с версией джавы и кодировками одинаковые для всех модулей, поэтому их лучше из дочерних  pom вынести в родительский

2024-11-22 06:04 UTC, VadimZharkov reviewed
В стат. клиенте ненужные зависимости от реактивного стэка
spring-boot-starter-webflux и reactor-test. Ничего из них в клиенте не используется.

2024-11-22 06:08 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/mainservice/dto/comment/CommentDto.java
> +@Getter
В Dto вместо `@Getter @Setter` можно обойтись одной аннотацией `@Data` (или `@Value`  или типом record)

2024-11-22 06:56 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/mainservice/service/CommentService.java
> +        User user = userService.getUserById(userId);
Было бы хорошо проверять пользователя на существование
```
        User author = userRepository.findById(userId)
                .orElseThrow(() -> new NotFoundException("User", userId));
```

2024-11-22 07:00 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить

2024-11-22 18:23 UTC, zoomja commented on main-service/src/main/java/ru/practicum/mainservice/service/CommentService.java
> +        User user = userService.getUserById(userId);
в методе getUserById из юзер сервиса есть проверка на существование пользователя.

    public User getUserById(Integer id) {
        return userRepository.findById(id).orElseThrow(() -> new NotFoundException("User not found"));
    }

2024-11-23 04:53 UTC, VadimZharkov approved these changes

2024-11-23 10:03 UTC, merged